variavel=input('Digite Algo: ')
print(type(variavel))
print(variavel.isalpha())
print(variavel.isalnum())
print(variavel.isascii())
print(variavel.istitle())
print(variavel.islower())
print(variavel.isdecimal())
print(variavel.isupper())